// Generated by LiveScript 1.3.1
var map, parse, parseLine;
map = require('prelude-ls').map;
parse = require('./kage2json').parse;
parseLine = function(line){
  var ref$, id, related, data;
  ref$ = map(function(it){
    return it.trim();
  })(
  line.split('|')), id = ref$[0], related = ref$[1], data = ref$[2];
  return {
    id: id,
    related: related,
    raw: data,
    data: parse(data)
  };
};
module.exports = {
  parseLine: parseLine
};